{
 "title": "CP Dashboard - Machines Overview",
 "tags": [ "Skyline" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "d_environment",
    "label": "Environment:",
    "query": {
     "query": "label_values(system_uptime,environment)"
    }
   },
   {
    "name": "d_hostname",
    "label": "Hostname:",
    "query": {
     "query": "label_values(system_uptime{environment=~\"$d_environment\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Assets Count",
   "type": "table",
   "description": "Number of overall monitored assets",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (role)(system_gaia_os_role{role=~\".+\", host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3 Overall CPU Usage",
   "type": "bargauge",
   "description": "Top 3 assets CPU usage",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3,avg by (host_name) (100-system_cpu_utilization{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\", state=\"idle\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 3 Overall RAM Usage",
   "type": "bargauge",
   "description": "Top 3 assets RAM usage",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3,(system_memory_usage{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\", state=\"used\"} / ignoring (state) system_memory_limit{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"} * 100))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  { "title": "$d_hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "d_hostname" },
  {
   "title": "Role",
   "type": "stat",
   "description": "Machine Role",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_gaia_os_role{role=~\".+\", host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AVG(100-system_cpu_utilization{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\", state=\"idle\"})"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\", state=\"used\"}/ ignoring (state) system_memory_limit{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"} * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_paging_usage{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\", state=\"used\"}/ ignoring (state) system_paging_limit{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"} * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_filesystem_usage{host_name=~\"$d_hostname\", environment=~\"$d_environment\", mountpoint=\"/\", service_namespace=\"vs_id_0\", state=\"used\"}/ ignoring (state) system_filesystem_limit{host_name=~\"$d_hostname\", environment=~\"$d_environment\", mountpoint=\"/\", service_namespace=\"vs_id_0\"} * 100"
    }
   ]
  },
  {
   "title": "Logs FS Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_filesystem_usage{host_name=~\"$d_hostname\", environment=~\"$d_environment\", mountpoint=\"/var/log\", service_namespace=\"vs_id_0\", state=\"used\"}/ ignoring (state) system_filesystem_limit{host_name=~\"$d_hostname\", environment=~\"$d_environment\", mountpoint=\"/var/log\", service_namespace=\"vs_id_0\"} * 100"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (interface) (system_network_interface_io_receive_rate{host_name=~\"$d_hostname\", environment=~\"$d_environment\", interface!~\"TOTAL|lo\"})",
     "legendFormat": "RX {{interface}}"
    },
    {
     "expr": "sum by (interface) (system_network_interface_io_transmit_rate{host_name=~\"$d_hostname\", environment=~\"$d_environment\", interface!~\"TOTAL|lo\"})",
     "legendFormat": "TX {{interface}}"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "description": "Version of the OS",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_gaia_os_version{version=~\".+\", host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "stat",
   "description": "Hardware Model",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hardware_model{model=~\".+\", host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Policy Installed",
   "type": "stat",
   "description": "Installed policy name",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "firewall_policy_name{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Policy date",
   "type": "stat",
   "description": "Time of last policy installation",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(firewall_policy_time{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}>100000)*1000"
    }
   ]
  }
 ]
}